### ISSUE TITLE
Don't process QBFT messages after instance is decided

### ISSUE THREAD

**Issue by GalRogozinski** [ssvlabs/ssv-spec#473]
## Description

Even after an instance is decided we process messages. This is in order to gather more commit messages for Explorer usage.
It is unclear why spec should be concerned with explorer. Allowing to process messages after decided can lead to sudden unexpected behaviors like creating extra round changes.

**Comment by olegshmuelov** [comment]
Just to clarify, the exporter is now operating differently, and we no longer need to gather additional commit messages after an instance is decided. This change was implemented with the merging of PR [#1409](https://github.com/ssvlabs/ssv/pull/1409) into the stage (pre-fork) branch.

Additionally, as a reminder, it's still necessary to process post-consensus messages after an instance has been decided.

**Comment by GalRogozinski** [comment]
@olegshmuelov 
of course I am only talking about QBFT messages the instance processes
