### ISSUE TITLE
PRs that should be merged for CC

### ISSUE THREAD

**Issue by GalRogozinski** [ssvlabs/ssv-spec#479]
The following PRs should be merged to `dev` branch and then to main.
There are already fixes merged on the `dev` branch not mentioned here that should go to main.

Audit:

- [x] #478 
- [x] #477
- [x] #476
- [x] #475
- [x] #474

Fixes:
- [ ] #471
- [x] #472
- [x] #473 
- [ ] #367 (another slashing check small fix)

**Comment by Tom-ssvlabs** [comment]
By @MatheusFranco99 :
The 2 left PRs are done but waiting for review. One has been reviewed and Gal will align to the comments next week and the other is mine and Gal needs to review it when he's back.

@GalRogozinski

**Comment by GalRogozinski** [comment]
CC is done
The 2 leftovers will be merged later
