### ISSUE TITLE
A spec probably shouldn't care about whether the key is PKCS1 or PKCS8 encoded

### ISSUE THREAD

**Issue by GalRogozinski** [ssvlabs/ssv-spec#485]
A spec probably shouldn't care about whether the key is PKCS1 or PKCS8 encoded

We maybe should consider deleting this code

_Originally posted by @GalRogozinski in https://github.com/ssvlabs/ssv-spec/pull/481#discussion_r1718189128_

**Comment by y0sher** [comment]
IMO this SHOULD be something declared in the spec, so this is standardized ( for example across clients ). I agree spec shouldn't care about which implementation to use, but it should tell all client implementers that they should accept a key encoded in some specific format.

**Comment by GalRogozinski** [comment]
I agree and I am closing this issue
